In [2]:
#hide
!pip install -q fastbook
import fastbook
# fastbook.setup_book()

     |████████████████████████████████| 727kB 6.5MB/s 
     |████████████████████████████████| 1.2MB 25.4MB/s 
     |████████████████████████████████| 194kB 44.4MB/s 
     |████████████████████████████████| 51kB 5.2MB/s 
     |████████████████████████████████| 776.8MB 22kB/s 
     |████████████████████████████████| 12.8MB 45.8MB/s 
     |████████████████████████████████| 61kB 6.4MB/s 
     |████████████████████████████████| 51kB 5.4MB/s 
ERROR: torchtext 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.7.1 which is incompatible.


In [3]:
#hide
from fastbook import *

## Questionnaire

1. Write the Python code to implement a single neuron.

In [ ]:
neuron_output = sum([x*w for x,w in zip(inputs,weights)]) + bias

__2. Write the Python code to implement ReLU.__

In [ ]:
def relu(x): return 0 if x<0 else x

__3. Write the Python code for a dense layer in terms of matrix multiplication.__

In [ ]:
y = x @ w.t() + b

__4. Write the Python code for a dense layer in plain Python (that is, with list comprehensions and functionality built into Python).__

In [ ]:
y[i,j] = sum([a * b for a,b in zip(x[i,:],w[j,:])]) + b[j]

__5. What is the "hidden size" of a layer?__

The number of neurons in that layer

__6. What does the `t` method do in PyTorch?__

Tranposes the matrix

__7. Why is matrix multiplication written in plain Python very slow?__

It's too high level. C++ is used in Pytorch to speed things up.

__8. In `matmul`, why is `ac==br`?__

The number of columns in matrix `a` must equal the number of rows in matrix `b`

__9. In Jupyter Notebook, how do you measure the time taken for a single cell to execute?__

`%time`

__10. What is "elementwise arithmetic"?__

When a mathematical operation is applied to every cell in the tensor.

__11. Write the PyTorch code to test whether every element of `a` is greater than the corresponding element of `b`.__

In [ ]:
(a < b).all()

__12. What is a rank-0 tensor? How do you convert it to a plain Python data type?__

A rank-0 tensor is a tensor that returns one element

You can turn it into a plain Python data type using the `.item()` command

__13. What does this return, and why? `tensor([1,2]) + tensor([1])`__

Should given an error. The tensors don't have the same shapes.

__14. What does this return, and why? `tensor([1,2]) + tensor([1,2,3])`__

Same as above

__15. How does elementwise arithmetic help us speed up `matmul`?__

We can do this: `a[i,:] * b[:,j]`. This takes the product of one row from `a` and one column at `b` at each cell. Then we call `.sum()` on the result. This removes an entire loop from the `matmul` function.

__16. What are the broadcasting rules?__

Pytorch compares tensor shapes elementwise. It starts with the ending dimensions and works it way backward. It will add 1 where it sees empty dimensions. Stopping criteria:

- Tensors are equal
- One of the tensors is 1


__17. What is `expand_as`? Show an example of how it can be used to match the results of broadcasting.__

In [ ]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
c.expand_as(m)
# [22]: tensor([[10., 20., 30.],
#         [10., 20., 30.],
#         [10., 20., 30.]])

__18. How does `unsqueeze` help us to solve certain broadcasting problems?__

It adds a unit dimension to our tensor. This helps if we need to broadcast tensors of different shapes.

__19. How can we use indexing to do the same operation as `unsqueeze`?__

In [ ]:
# the following explains it

In [5]:
c = torch.randn(64,28,28)
c.shape

torch.Size([64, 28, 28])

In [6]:
c.unsqueeze(1).shape

torch.Size([64, 1, 28, 28])

In [7]:
c[:,None].shape

torch.Size([64, 1, 28, 28])

In [8]:
c[:,:, None].shape

torch.Size([64, 28, 1, 28])

In [9]:
c[...,None].shape

torch.Size([64, 28, 28, 1])

__20. How do we show the actual contents of the memory used for a tensor?__

In [10]:
c.storage()

 1.9269152879714966
 1.4872840642929077
 0.9007171988487244
 -2.1055209636688232
 0.6784184575080872
 -1.2345448732376099
 -0.04306747764348984
 -1.6046669483184814
 -0.7521352767944336
 1.6487230062484741
 -0.3924786448478699
 -1.4036071300506592
 -0.7278813123703003
 -0.5594301819801331
 -0.7688388824462891
 0.7624453902244568
 1.6423169374465942
 -0.1595974713563919
 -0.4973975419998169
 0.439589262008667
 -0.7581311464309692
 1.078317642211914
 0.8008005619049072
 1.680620551109314
 1.27912437915802
 1.2964228391647339
 0.610466480255127
 1.334737777709961
 -0.2316243201494217
 0.041759490966796875
 -0.2515752911567688
 0.859858512878418
 -1.3846737146377563
 -0.8712361454963684
 -0.223365917801857
 1.7173614501953125
 0.3188803195953369
 -0.42451897263526917
 0.3057209253311157
 -0.7745925188064575
 -1.5575724840164185
 0.9956361055374146
 -0.8797858357429504
 -0.6011420488357544
 -1.2741512060165405
 2.1227850914001465
 -1.234653115272522
 -0.4879138767719269
 -0.9138230085372925

__21. When adding a vector of size 3 to a matrix of size 3×3, are the elements of the vector added to each row or each column of the matrix? (Be sure to check your answer by running this code in a notebook.)__

The elements of the vector are added to each row of the matrix as follows:

In [11]:
c = torch.randn(3)
d = torch.randn(3,3)
c.shape, d.shape

(torch.Size([3]), torch.Size([3, 3]))

In [12]:
c

tensor([-1.0413,  0.1454,  1.7158])

In [13]:
d

tensor([[-0.6817, -0.3108,  0.8937],
        [-0.5705,  0.1401, -0.1598],
        [-0.9723, -2.2842, -0.0553]])

In [14]:
c+d

tensor([[-1.7229, -0.1654,  2.6096],
        [-1.6117,  0.2855,  1.5560],
        [-2.0136, -2.1388,  1.6606]])

__22. Do broadcasting and `expand_as` result in increased memory use? Why or why not?__

No it does not. Pytorch gives the tensor a stride of 0. So when it looks for the next row by adding the stride - it doesn't move.

__23. Implement `matmul` using Einstein summation.__

In [15]:
def matmul(a,b): return torch.einsum('ik,kj->ij', a, b)

__24. What does a repeated index letter represent on the left-hand side of einsum?__

The number of rows in one matrix need to equal the number of cols in another matrix. Eg. in the question above the letter `k` is repeated on the LHS.

__25. What are the three rules of Einstein summation notation? Why?__

Repeated indices are implicitly summed over. Above, the term k is repeated so we sum over that index.

Each index can appear at most twice in any term. 

Each term must contain identical nonrepeated indices.


TODO: fill in why

__26. What are the forward pass and backward pass of a neural network?__

forward pass: compute the output of a model given input and weights

backward pass: compute gradients of each layer starting at the end of the model.

__27. Why do we need to store some of the activations calculated for intermediate layers in the forward pass?__

So we can calculate the gradients in the backward pass

__28. What is the downside of having activations with a standard deviation too far away from 1?__

We run the risk of the activations becoming `nans` as they are too large

__29. How can weight initialization help avoid this problem?__

We can mulitply each layer by a scale value: `1/√𝑛𝑖𝑛`

__30. What is the formula to initialize weights such that we get a standard deviation of 1 for a plain linear layer, and for a linear layer followed by ReLU?__

Multiply each layer by the scale value: `2/√𝑛𝑖𝑛`. Kaiming init.

__31. Why do we sometimes have to use the `squeeze` method in loss functions?__

To get rid of the trailing unit dimension

__32. What does the argument to the `squeeze` method do? Why might it be important to include this argument, even though PyTorch does not require it?__

The argument tells PyTorch what axis to remove the unit dimensions from. It can be sometimes useful to hardcode this yourself for clarity?

__33. What is the "chain rule"? Show the equation in either of the two forms presented in this chapter.__

$$\frac{\text{d} loss}{\text{d} b_{2}} = \frac{\text{d} loss}{\text{d} out} \times \frac{\text{d} out}{\text{d} b_{2}} = \frac{\text{d}}{\text{d} out} mse(out, y) \times \frac{\text{d}}{\text{d} b_{2}} lin(l_{2}, w_{2}, b_{2})$$


__34. Show how to calculate the gradients of `mse(lin(l2, w2, b2), y)` using the chain rule.__

In [105]:
from math import sqrt

In [159]:
def relu(x): return x.clamp_min(0.)
def lin(x, w, b): return x @ w + b
def mse(output, targ): return (output.squeeze() - targ).pow(2).mean()

def mse_grad(inp, targ): 
    # grad of loss with respect to output of previous layer
    inp.g = 2. * (inp.squeeze() - targ).unsqueeze(-1) / inp.shape[0]

def relu_grad(inp, out):
    # grad of relu with respect to input activations
    inp.g = (inp>0).float() * out.g

def lin_grad(inp, out, w, b):
    # grad of matmul with respect to input
    inp.g = out.g @ w.t()
    w.g = inp.t() @ out.g
    b.g = out.g.sum(0)

In [107]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [108]:
w1 = torch.randn(100,50) * sqrt(2 / 100)
b1 = torch.zeros(50)
w2 = torch.randn(50,1) * sqrt(2 / 50)
b2 = torch.zeros(1)

In [110]:
# forward pass
l1 = lin(x, w1, b1)
l2 = relu(l1)
l3 = lin(l2, w2, b2)
out.shape

torch.Size([200, 1])

In [111]:
# loss
loss = mse(out, y)

In [112]:
# gradients calculated here
# backward pass
mse_grad(out, y) # d(loss)/d(out)
lin_grad(l2, out, w2, b2) # d(out)/d(b2)
relu_grad(l1, l2) # d(relu)/d(out)
lin_grad(x, l1, w1, b1) # d(out)/d(b1)

In [116]:
w1.g.shape, l1.g.shape, l2.g.shape, out.g.shape

(torch.Size([100, 50]),
 torch.Size([200, 50]),
 torch.Size([200, 50]),
 torch.Size([200, 1]))

__35. What is the gradient of ReLU? Show it in math or code. (You shouldn't need to commit this to memory—try to figure it using your knowledge of the shape of the function.)__

In [ ]:
# when inputs are negative derivative is 0
# when inputs are postive derivative is 1
inp.g = (inp>0).float() * out.g

__36. In what order do we need to call the `*_grad` functions in the backward pass? Why?__

We call the last layer in the model first. So we use the mse_grad function first. We need this order for the chain rule to work.


__37. What is `__call__`?__

It's a function that makes the `Class` callable.

__38. What methods must we implement when writing a `torch.autograd.Function`?__

`forward` and `backward` methods

__39. Write `nn.Linear` from scratch, and test it works.__

In [156]:
class Linear():
    def __init__(self, w, b): 
        self.w,self.b = w,b
        
    def __call__(self, inp):
        self.inp = inp
        self.out = inp@self.w + self.b
        return self.out
    
    def backward(self):
        self.inp.g = self.out.g @ self.w.t()
        self.w.g = self.inp.t() @ self.out.g
        self.b.g = self.out.g.sum(0)

In [184]:
n_out = 50
x = torch.randn(200, 100)
y = torch.randn(200)

In [186]:
n_out = 50
n_in = 100
w1 = torch.randn(n_in, n_out) * sqrt(2/n_in)
b1 = torch.zeros(n_out)

In [187]:
l1 = Linear(w1,b1)

In [189]:
y1 = l1(x)
y1.shape

torch.Size([200, 50])

In [190]:
l2 = nn.Linear(100, n_out)
y2 = l2(x)
y2.shape

torch.Size([200, 50])

In [191]:
assert(y1.shape == y2.shape)

__40. What is the difference between `nn.Module` and fastai's `Module`?__

You don't have to call `super.__init__()` in fastai's version